#!/bin/bash

# This script helps set up the environment for building with Xcode
# Run this script before opening the Xcode project or after experiencing build errors

echo "Setting up iOS build environment for AA Recovery Tracker..."

# Verify node is installed
if ! command -v node &> /dev/null; then
    echo "Error: Node.js is not installed or not in PATH"
    echo "Please install Node.js and try again"
    exit 1
fi

# Get current directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "Project directory: $PROJECT_DIR"
echo "iOS directory: $SCRIPT_DIR"

# Clean node_modules/.cache if it exists to prevent stale cache issues
if [ -d "$PROJECT_DIR/node_modules/.cache" ]; then
    echo "Cleaning node_modules cache..."
    rm -rf "$PROJECT_DIR/node_modules/.cache"
fi

# Create .xcode.env file with proper NODE_BINARY path
echo "Creating .xcode.env file with Node path..."
NODE_PATH=$(command -v node)
cat > "$SCRIPT_DIR/.xcode.env" << EOL
# This file is automatically generated
export NODE_BINARY=$NODE_PATH
EOL

echo "Created .xcode.env with NODE_BINARY=$NODE_PATH"

# Clean the Xcode build directory
echo "Cleaning DerivedData..."
rm -rf ~/Library/Developer/Xcode/DerivedData/AARecoveryTracker-*

# Reinstall pods if needed
if [ "$1" == "--clean-pods" ]; then
    echo "Removing Pods directory..."
    rm -rf "$SCRIPT_DIR/Pods"
    
    echo "Running pod deintegrate..."
    cd "$SCRIPT_DIR" && pod deintegrate
    
    echo "Running pod install with repo update..."
    cd "$SCRIPT_DIR" && pod install --repo-update
else
    echo "Running pod install..."
    cd "$SCRIPT_DIR" && pod install
fi

# Fix any issues with the Expo configure scripts
echo "Fixing Expo configure scripts..."
cd "$SCRIPT_DIR" && ./fix-expo-configure.sh

echo ""
echo "Setup complete! You can now open the workspace in Xcode:"
echo "open $SCRIPT_DIR/AARecoveryTracker.xcworkspace"
echo ""
echo "If you're still experiencing build issues, try running this script with:"
echo "./setup-build-env.sh --clean-pods"