require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

# We need to modify the use_native_modules function to avoid dependency on ReactAppDependencyProvider
react_native_path = File.join(File.dirname(`node --print "require.resolve('react-native/package.json')`))

# Override use_native_modules to skip codegen-related dependencies
def patch_use_native_modules
  # Get the original method
  original_method = Object.method(:use_native_modules)
  
  # Define our patched version
  Object.define_singleton_method(:use_native_modules) do |config = {}|
    # Call the original but handle any exceptions related to ReactAppDependencyProvider
    begin
      original_method.call(config)
    rescue StandardError => e
      if e.message.include?('ReactAppDependencyProvider')
        puts "Ignoring ReactAppDependencyProvider dependency error"
      else
        raise e
      end
    end
  end
end

# Apply our patch
patch_use_native_modules

# Now load the required scripts
require File.join(react_native_path, "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

# Disable new architecture and related features
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['USE_HERMES'] = '0'
ENV['USE_BRIDGELESS'] = '0'
ENV['USE_FRAMEWORKS'] = 'static'
ENV['CODEGEN_DISABLE_ALL'] = '1'  # Disable all codegen

# Disable Flipper
ENV['NO_FLIPPER'] = "1"

platform :ios, '16.0'
prepare_react_native_project!

target 'SpiritualConditionTracker' do
  use_expo_modules!
  
  # Use React Native with JSC (not Hermes), explicitly disable Fabric
  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  # Explicitly exclude problematic dependencies
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.include?('ReactAppDependencyProvider') || 
         pod.name.include?('React-Fabric') || 
         pod.name.include?('React-RCTFabric') ||
         pod.name.include?('FBReactNativeSpec')
        pod.specs.each do |spec|
          spec.attributes_hash['platforms'] = { 'ios' => '99.0' }  # Set an impossible platform version
        end
      end
    end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Set deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
  
  # Standard React Native post install
  react_native_post_install(
    installer,
    react_native_path,
    :mac_catalyst_enabled => false
  )
end