version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: spiritual-condition-tracker
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - EXPO_PORT=5001
    volumes:
      - app-data:/app/data

volumes:
  app-data: